### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by gcelano** [korpling/paula-xml#3]
The link http://www.sfb632.uni-potsdam.de/downloads/paula/PAULA_P1.1.2013.1.21a.pdf provided  does not work

**Comment by amir-zeldes** [comment]
It works for me...

![image](https://github.com/korpling/paula-xml/assets/2188635/59c7255a-2555-4fa6-8691-c754968301f5)

What does your browser say?

**Comment by gcelano** [comment]
The link in the README.md file works on Firefox but not on Chrome

**Comment by amir-zeldes** [comment]
I think that's not a general chrome thing - maybe the Chrome installation is set not to allow http without ssl (https)?

**Comment by gcelano** [comment]
The pdf is not open within the browser, but I can download it if the link is opened in another window. I am not sure what the cause is.

**Comment by thomaskrause** [comment]
Thanks for the report, I also suspect some issue with missing https. Since the old SFB server seems not to be configured to allow https access, I uploaded the original Paula PDF file to this repository and changed the link to point there:

https://raw.githubusercontent.com/korpling/paula-xml/master/PAULA_P1.1.2013.1.21a.pdf
